import { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type SupportedLanguage = 
  | 'en' 
  | 'ja' 
  | 'ru' 
  | 'fr' 
  | 'ta' 
  | 'ml' 
  | 'hi' 
  | 'te' 
  | 'es' 
  | 'zh' 
  | 'pt';

export const languageNames: Record<SupportedLanguage, string> = {
  en: 'English',
  ja: '日本語',
  ru: 'Русский',
  fr: 'Français',
  ta: 'தமிழ்',
  ml: 'മലയാളം',
  hi: 'हिन्दी',
  te: 'తెలుగు',
  es: 'Español',
  zh: '中文',
  pt: 'Português',
};

// Translation keys for the entire app
export const translations: Record<SupportedLanguage, Record<string, string>> = {
  en: {
    // Navigation
    'nav.tripPlanner': 'Trip Planner',
    'nav.workspaces': 'Workspaces',
    'nav.tools': 'Tools',
    
    // Hero Section
    'hero.title': 'Plan Your Perfect Trip',
    'hero.subtitle': 'AI-powered travel recommendations',
    'hero.getStarted': 'Get Started',
    
    // Tools Directory
    'tools.title': 'Cultural Tools',
    'tools.subtitle': 'Navigate local culture with AI-powered assistance',
    'tools.menuTranslator': 'Menu Translator',
    'tools.menuTranslatorDesc': 'Snap a photo of any menu and get instant translations with dietary information',
    'tools.slangGuide': 'Slang & Etiquette',
    'tools.slangGuideDesc': 'Quick-access guide to local phrases and customs',
    'tools.comingSoon': 'Coming Soon',
    'tools.openTool': 'Open Tool',
    
    // Menu Translator
    'menu.title': 'Menu Translator',
    'menu.subtitle': 'Upload a menu photo and get instant translations with dietary information',
    'menu.backToTools': 'Back to Tools',
    'menu.dietaryPrefs': 'Dietary Preferences',
    'menu.dietaryPrefsDesc': 'Select your dietary requirements to highlight compatible dishes',
    'menu.vegetarian': 'Vegetarian',
    'menu.vegan': 'Vegan',
    'menu.nonVeg': 'Non-Veg',
    'menu.glutenFree': 'Gluten-Free',
    'menu.noOnionGarlic': 'No Onion/Garlic',
    'menu.nutAllergy': 'Nut Allergy',
    'menu.dairyFree': 'Dairy-Free',
    'menu.uploadPhoto': 'Upload Menu Photo',
    'menu.uploadDesc': 'Take a photo or upload an image of any menu',
    'menu.takePhoto': 'Take Photo',
    'menu.uploadImage': 'Upload Image',
    'menu.translateMenu': 'Translate Menu',
    'menu.translating': 'Translating...',
    'menu.newPhoto': 'New Photo',
    'menu.reTranslate': 'Re-translate',
    'menu.dishesFound': 'Dishes Found',
    'menu.original': 'Original',
    'menu.list': 'List',
    'menu.overlay': 'Overlay',
    'menu.ingredients': 'Ingredients',
    'menu.fileTooLarge': 'File too large',
    'menu.fileTooLargeDesc': 'Please select an image under 10MB',
    'menu.translationFailed': 'Translation Failed',
    'menu.tryAgain': 'Please try again with a clearer image',
    'menu.menuTranslated': 'Menu Translated!',
    'menu.foundDishes': 'Found {count} dishes in {language}',
    
    // Common
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.close': 'Close',
    'common.language': 'Language',
    
    // Footer
    'footer.tagline': 'SakuraTrip • AI-Powered Travel Planning',
  },
  ja: {
    'nav.tripPlanner': '旅行プランナー',
    'nav.workspaces': 'ワークスペース',
    'nav.tools': 'ツール',
    'hero.title': '完璧な旅行を計画',
    'hero.subtitle': 'AI搭載の旅行提案',
    'hero.getStarted': '始める',
    'tools.title': '文化ツール',
    'tools.subtitle': 'AI支援で地域文化をナビゲート',
    'tools.menuTranslator': 'メニュー翻訳',
    'tools.menuTranslatorDesc': 'メニューの写真を撮って、食事情報付きの即座翻訳を取得',
    'tools.slangGuide': 'スラング＆エチケット',
    'tools.slangGuideDesc': '地域のフレーズと習慣のクイックアクセスガイド',
    'tools.comingSoon': '近日公開',
    'tools.openTool': 'ツールを開く',
    'menu.title': 'メニュー翻訳',
    'menu.subtitle': 'メニューの写真をアップロードして、食事情報付きの翻訳を取得',
    'menu.backToTools': 'ツールに戻る',
    'menu.dietaryPrefs': '食事の好み',
    'menu.dietaryPrefsDesc': '互換性のある料理をハイライトするために食事要件を選択',
    'menu.vegetarian': 'ベジタリアン',
    'menu.vegan': 'ビーガン',
    'menu.nonVeg': 'ノンベジ',
    'menu.glutenFree': 'グルテンフリー',
    'menu.noOnionGarlic': '玉ねぎ/にんにくなし',
    'menu.nutAllergy': 'ナッツアレルギー',
    'menu.dairyFree': '乳製品不使用',
    'menu.uploadPhoto': 'メニュー写真をアップロード',
    'menu.uploadDesc': '写真を撮るか、メニューの画像をアップロード',
    'menu.takePhoto': '写真を撮る',
    'menu.uploadImage': '画像をアップロード',
    'menu.translateMenu': 'メニューを翻訳',
    'menu.translating': '翻訳中...',
    'menu.newPhoto': '新しい写真',
    'menu.reTranslate': '再翻訳',
    'menu.dishesFound': '料理が見つかりました',
    'menu.original': 'オリジナル',
    'menu.list': 'リスト',
    'menu.overlay': 'オーバーレイ',
    'menu.ingredients': '材料',
    'menu.fileTooLarge': 'ファイルが大きすぎます',
    'menu.fileTooLargeDesc': '10MB未満の画像を選択してください',
    'menu.translationFailed': '翻訳に失敗',
    'menu.tryAgain': 'より鮮明な画像で再試行してください',
    'menu.menuTranslated': 'メニュー翻訳完了！',
    'menu.foundDishes': '{language}で{count}皿見つかりました',
    'common.loading': '読み込み中...',
    'common.error': 'エラー',
    'common.success': '成功',
    'common.cancel': 'キャンセル',
    'common.save': '保存',
    'common.delete': '削除',
    'common.edit': '編集',
    'common.close': '閉じる',
    'common.language': '言語',
    'footer.tagline': 'SakuraTrip • AI搭載旅行計画',
  },
  ru: {
    'nav.tripPlanner': 'Планировщик',
    'nav.workspaces': 'Рабочие места',
    'nav.tools': 'Инструменты',
    'hero.title': 'Спланируйте идеальную поездку',
    'hero.subtitle': 'Рекомендации на базе ИИ',
    'hero.getStarted': 'Начать',
    'tools.title': 'Культурные инструменты',
    'tools.subtitle': 'Навигация по местной культуре с помощью ИИ',
    'tools.menuTranslator': 'Переводчик меню',
    'tools.menuTranslatorDesc': 'Сфотографируйте меню и получите перевод с диетической информацией',
    'tools.slangGuide': 'Сленг и этикет',
    'tools.slangGuideDesc': 'Быстрый доступ к местным фразам и обычаям',
    'tools.comingSoon': 'Скоро',
    'tools.openTool': 'Открыть',
    'menu.title': 'Переводчик меню',
    'menu.subtitle': 'Загрузите фото меню и получите перевод с диетической информацией',
    'menu.backToTools': 'Назад к инструментам',
    'menu.dietaryPrefs': 'Диетические предпочтения',
    'menu.dietaryPrefsDesc': 'Выберите требования для выделения подходящих блюд',
    'menu.vegetarian': 'Вегетарианское',
    'menu.vegan': 'Веганское',
    'menu.nonVeg': 'Мясное',
    'menu.glutenFree': 'Без глютена',
    'menu.noOnionGarlic': 'Без лука/чеснока',
    'menu.nutAllergy': 'Аллергия на орехи',
    'menu.dairyFree': 'Без молочных',
    'menu.uploadPhoto': 'Загрузить фото меню',
    'menu.uploadDesc': 'Сделайте фото или загрузите изображение меню',
    'menu.takePhoto': 'Сделать фото',
    'menu.uploadImage': 'Загрузить',
    'menu.translateMenu': 'Перевести меню',
    'menu.translating': 'Перевод...',
    'menu.newPhoto': 'Новое фото',
    'menu.reTranslate': 'Перевести снова',
    'menu.dishesFound': 'Блюд найдено',
    'menu.original': 'Оригинал',
    'menu.list': 'Список',
    'menu.overlay': 'Наложение',
    'menu.ingredients': 'Ингредиенты',
    'menu.fileTooLarge': 'Файл слишком большой',
    'menu.fileTooLargeDesc': 'Выберите изображение до 10МБ',
    'menu.translationFailed': 'Ошибка перевода',
    'menu.tryAgain': 'Попробуйте с более чётким изображением',
    'menu.menuTranslated': 'Меню переведено!',
    'menu.foundDishes': 'Найдено {count} блюд на {language}',
    'common.loading': 'Загрузка...',
    'common.error': 'Ошибка',
    'common.success': 'Успех',
    'common.cancel': 'Отмена',
    'common.save': 'Сохранить',
    'common.delete': 'Удалить',
    'common.edit': 'Редактировать',
    'common.close': 'Закрыть',
    'common.language': 'Язык',
    'footer.tagline': 'SakuraTrip • ИИ-планирование путешествий',
  },
  fr: {
    'nav.tripPlanner': 'Planificateur',
    'nav.workspaces': 'Espaces',
    'nav.tools': 'Outils',
    'hero.title': 'Planifiez votre voyage parfait',
    'hero.subtitle': 'Recommandations alimentées par IA',
    'hero.getStarted': 'Commencer',
    'tools.title': 'Outils culturels',
    'tools.subtitle': 'Naviguez dans la culture locale avec l\'IA',
    'tools.menuTranslator': 'Traducteur de menu',
    'tools.menuTranslatorDesc': 'Photographiez un menu et obtenez une traduction instantanée',
    'tools.slangGuide': 'Argot et étiquette',
    'tools.slangGuideDesc': 'Guide rapide des expressions et coutumes locales',
    'tools.comingSoon': 'Bientôt',
    'tools.openTool': 'Ouvrir',
    'menu.title': 'Traducteur de menu',
    'menu.subtitle': 'Téléchargez une photo de menu pour une traduction instantanée',
    'menu.backToTools': 'Retour aux outils',
    'menu.dietaryPrefs': 'Préférences alimentaires',
    'menu.dietaryPrefsDesc': 'Sélectionnez vos exigences pour mettre en évidence les plats compatibles',
    'menu.vegetarian': 'Végétarien',
    'menu.vegan': 'Végan',
    'menu.nonVeg': 'Non-végé',
    'menu.glutenFree': 'Sans gluten',
    'menu.noOnionGarlic': 'Sans oignon/ail',
    'menu.nutAllergy': 'Allergie aux noix',
    'menu.dairyFree': 'Sans produits laitiers',
    'menu.uploadPhoto': 'Télécharger une photo de menu',
    'menu.uploadDesc': 'Prenez une photo ou téléchargez une image de menu',
    'menu.takePhoto': 'Prendre photo',
    'menu.uploadImage': 'Télécharger',
    'menu.translateMenu': 'Traduire le menu',
    'menu.translating': 'Traduction...',
    'menu.newPhoto': 'Nouvelle photo',
    'menu.reTranslate': 'Retraduire',
    'menu.dishesFound': 'Plats trouvés',
    'menu.original': 'Original',
    'menu.list': 'Liste',
    'menu.overlay': 'Superposition',
    'menu.ingredients': 'Ingrédients',
    'menu.fileTooLarge': 'Fichier trop volumineux',
    'menu.fileTooLargeDesc': 'Veuillez sélectionner une image de moins de 10 Mo',
    'menu.translationFailed': 'Échec de la traduction',
    'menu.tryAgain': 'Réessayez avec une image plus claire',
    'menu.menuTranslated': 'Menu traduit !',
    'menu.foundDishes': '{count} plats trouvés en {language}',
    'common.loading': 'Chargement...',
    'common.error': 'Erreur',
    'common.success': 'Succès',
    'common.cancel': 'Annuler',
    'common.save': 'Enregistrer',
    'common.delete': 'Supprimer',
    'common.edit': 'Modifier',
    'common.close': 'Fermer',
    'common.language': 'Langue',
    'footer.tagline': 'SakuraTrip • Planification de voyage IA',
  },
  ta: {
    'nav.tripPlanner': 'பயண திட்டமிடல்',
    'nav.workspaces': 'பணியிடங்கள்',
    'nav.tools': 'கருவிகள்',
    'hero.title': 'சரியான பயணத்தை திட்டமிடுங்கள்',
    'hero.subtitle': 'AI சக்தி கொண்ட பயண பரிந்துரைகள்',
    'hero.getStarted': 'தொடங்கு',
    'tools.title': 'கலாச்சார கருவிகள்',
    'tools.subtitle': 'AI உதவியுடன் உள்ளூர் கலாச்சாரத்தை வழிநடத்துங்கள்',
    'tools.menuTranslator': 'மெனு மொழிபெயர்ப்பாளர்',
    'tools.menuTranslatorDesc': 'மெனுவின் புகைப்படம் எடுத்து உடனடி மொழிபெயர்ப்பு பெறுங்கள்',
    'tools.slangGuide': 'வட்டார மொழி வழிகாட்டி',
    'tools.slangGuideDesc': 'உள்ளூர் சொற்றொடர்கள் மற்றும் பழக்கவழக்கங்களுக்கான விரைவு வழிகாட்டி',
    'tools.comingSoon': 'விரைவில் வருகிறது',
    'tools.openTool': 'கருவியைத் திற',
    'menu.title': 'மெனு மொழிபெயர்ப்பாளர்',
    'menu.subtitle': 'மெனு புகைப்படத்தை பதிவேற்றி உடனடி மொழிபெயர்ப்பு பெறுங்கள்',
    'menu.backToTools': 'கருவிகளுக்கு திரும்பு',
    'menu.dietaryPrefs': 'உணவு விருப்பங்கள்',
    'menu.dietaryPrefsDesc': 'பொருத்தமான உணவுகளை தெளிவுபடுத்த உங்கள் தேவைகளை தேர்ந்தெடுக்கவும்',
    'menu.vegetarian': 'சைவம்',
    'menu.vegan': 'வீகன்',
    'menu.nonVeg': 'அசைவம்',
    'menu.glutenFree': 'க்ளூட்டன் இல்லாத',
    'menu.noOnionGarlic': 'வெங்காயம்/பூண்டு இல்லாத',
    'menu.nutAllergy': 'நட்ஸ் ஒவ்வாமை',
    'menu.dairyFree': 'பால் இல்லாத',
    'menu.uploadPhoto': 'மெனு புகைப்படம் பதிவேற்றவும்',
    'menu.uploadDesc': 'புகைப்படம் எடுக்கவும் அல்லது மெனு படத்தை பதிவேற்றவும்',
    'menu.takePhoto': 'புகைப்படம் எடு',
    'menu.uploadImage': 'பதிவேற்று',
    'menu.translateMenu': 'மெனுவை மொழிபெயர்',
    'menu.translating': 'மொழிபெயர்க்கிறது...',
    'menu.newPhoto': 'புதிய புகைப்படம்',
    'menu.reTranslate': 'மீண்டும் மொழிபெயர்',
    'menu.dishesFound': 'உணவுகள் கண்டுபிடிக்கப்பட்டன',
    'menu.original': 'அசல்',
    'menu.list': 'பட்டியல்',
    'menu.overlay': 'மேலடுக்கு',
    'menu.ingredients': 'பொருட்கள்',
    'menu.fileTooLarge': 'கோப்பு மிகப் பெரியது',
    'menu.fileTooLargeDesc': '10MB க்கு கீழ் படத்தை தேர்ந்தெடுக்கவும்',
    'menu.translationFailed': 'மொழிபெயர்ப்பு தோல்வி',
    'menu.tryAgain': 'தெளிவான படத்துடன் மீண்டும் முயற்சிக்கவும்',
    'menu.menuTranslated': 'மெனு மொழிபெயர்க்கப்பட்டது!',
    'menu.foundDishes': '{language} இல் {count} உணவுகள் கண்டுபிடிக்கப்பட்டன',
    'common.loading': 'ஏற்றுகிறது...',
    'common.error': 'பிழை',
    'common.success': 'வெற்றி',
    'common.cancel': 'ரத்து செய்',
    'common.save': 'சேமி',
    'common.delete': 'நீக்கு',
    'common.edit': 'திருத்து',
    'common.close': 'மூடு',
    'common.language': 'மொழி',
    'footer.tagline': 'SakuraTrip • AI பயண திட்டமிடல்',
  },
  ml: {
    'nav.tripPlanner': 'യാത്രാ പ്ലാനർ',
    'nav.workspaces': 'വർക്ക്‌സ്‌പേസുകൾ',
    'nav.tools': 'ഉപകരണങ്ങൾ',
    'hero.title': 'നിങ്ങളുടെ യാത്ര ആസൂത്രണം ചെയ്യുക',
    'hero.subtitle': 'AI-പവർഡ് യാത്രാ ശുപാർശകൾ',
    'hero.getStarted': 'ആരംഭിക്കുക',
    'tools.title': 'സാംസ്കാരിക ഉപകരണങ്ങൾ',
    'tools.subtitle': 'AI സഹായത്തോടെ പ്രാദേശിക സംസ്കാരം നാവിഗേറ്റ് ചെയ്യുക',
    'tools.menuTranslator': 'മെനു വിവർത്തകൻ',
    'tools.menuTranslatorDesc': 'മെനുവിന്റെ ഫോട്ടോ എടുത്ത് തൽക്ഷണ വിവർത്തനം നേടുക',
    'tools.slangGuide': 'സ്ലാങ് & മര്യാദ',
    'tools.slangGuideDesc': 'പ്രാദേശിക വാക്യങ്ങളും ആചാരങ്ങളും',
    'tools.comingSoon': 'ഉടൻ വരുന്നു',
    'tools.openTool': 'തുറക്കുക',
    'menu.title': 'മെനു വിവർത്തകൻ',
    'menu.subtitle': 'മെനു ഫോട്ടോ അപ്‌ലോഡ് ചെയ്ത് തൽക്ഷണ വിവർത്തനം നേടുക',
    'menu.backToTools': 'ഉപകരണങ്ങളിലേക്ക് മടങ്ങുക',
    'menu.dietaryPrefs': 'ഭക്ഷണ മുൻഗണനകൾ',
    'menu.dietaryPrefsDesc': 'അനുയോജ്യമായ വിഭവങ്ങൾ ഹൈലൈറ്റ് ചെയ്യാൻ തിരഞ്ഞെടുക്കുക',
    'menu.vegetarian': 'സസ്യഭക്ഷണം',
    'menu.vegan': 'വീഗൻ',
    'menu.nonVeg': 'മാംസാഹാരം',
    'menu.glutenFree': 'ഗ്ലൂട്ടൻ ഇല്ലാത്ത',
    'menu.noOnionGarlic': 'ഉള്ളി/വെളുത്തുള്ളി ഇല്ലാത്ത',
    'menu.nutAllergy': 'നട്ട് അലർജി',
    'menu.dairyFree': 'പാൽ ഇല്ലാത്ത',
    'menu.uploadPhoto': 'മെനു ഫോട്ടോ അപ്‌ലോഡ് ചെയ്യുക',
    'menu.uploadDesc': 'ഫോട്ടോ എടുക്കുക അല്ലെങ്കിൽ മെനു ചിത്രം അപ്‌ലോഡ് ചെയ്യുക',
    'menu.takePhoto': 'ഫോട്ടോ എടുക്കുക',
    'menu.uploadImage': 'അപ്‌ലോഡ്',
    'menu.translateMenu': 'മെനു വിവർത്തനം ചെയ്യുക',
    'menu.translating': 'വിവർത്തനം ചെയ്യുന്നു...',
    'menu.newPhoto': 'പുതിയ ഫോട്ടോ',
    'menu.reTranslate': 'വീണ്ടും വിവർത്തനം',
    'menu.dishesFound': 'വിഭവങ്ങൾ കണ്ടെത്തി',
    'menu.original': 'ഒറിജിനൽ',
    'menu.list': 'ലിസ്റ്റ്',
    'menu.overlay': 'ഓവർലേ',
    'menu.ingredients': 'ചേരുവകൾ',
    'menu.fileTooLarge': 'ഫയൽ വളരെ വലുതാണ്',
    'menu.fileTooLargeDesc': '10MB-യിൽ താഴെയുള്ള ചിത്രം തിരഞ്ഞെടുക്കുക',
    'menu.translationFailed': 'വിവർത്തനം പരാജയപ്പെട്ടു',
    'menu.tryAgain': 'വ്യക്തമായ ചിത്രം ഉപയോഗിച്ച് വീണ്ടും ശ്രമിക്കുക',
    'menu.menuTranslated': 'മെനു വിവർത്തനം ചെയ്തു!',
    'menu.foundDishes': '{language}-ൽ {count} വിഭവങ്ങൾ കണ്ടെത്തി',
    'common.loading': 'ലോഡ് ചെയ്യുന്നു...',
    'common.error': 'പിശക്',
    'common.success': 'വിജയം',
    'common.cancel': 'റദ്ദാക്കുക',
    'common.save': 'സേവ് ചെയ്യുക',
    'common.delete': 'ഇല്ലാതാക്കുക',
    'common.edit': 'എഡിറ്റ് ചെയ്യുക',
    'common.close': 'അടയ്ക്കുക',
    'common.language': 'ഭാഷ',
    'footer.tagline': 'SakuraTrip • AI യാത്രാ ആസൂത്രണം',
  },
  hi: {
    'nav.tripPlanner': 'यात्रा योजनाकार',
    'nav.workspaces': 'कार्यस्थल',
    'nav.tools': 'उपकरण',
    'hero.title': 'अपनी सही यात्रा की योजना बनाएं',
    'hero.subtitle': 'AI-संचालित यात्रा सुझाव',
    'hero.getStarted': 'शुरू करें',
    'tools.title': 'सांस्कृतिक उपकरण',
    'tools.subtitle': 'AI सहायता से स्थानीय संस्कृति को समझें',
    'tools.menuTranslator': 'मेनू अनुवादक',
    'tools.menuTranslatorDesc': 'मेनू की फोटो लें और तुरंत अनुवाद प्राप्त करें',
    'tools.slangGuide': 'स्लैंग और शिष्टाचार',
    'tools.slangGuideDesc': 'स्थानीय वाक्यांशों और रीति-रिवाजों की त्वरित मार्गदर्शिका',
    'tools.comingSoon': 'जल्द आ रहा है',
    'tools.openTool': 'खोलें',
    'menu.title': 'मेनू अनुवादक',
    'menu.subtitle': 'मेनू फोटो अपलोड करें और तुरंत अनुवाद प्राप्त करें',
    'menu.backToTools': 'उपकरणों पर वापस',
    'menu.dietaryPrefs': 'आहार प्राथमिकताएं',
    'menu.dietaryPrefsDesc': 'संगत व्यंजनों को हाइलाइट करने के लिए अपनी आवश्यकताएं चुनें',
    'menu.vegetarian': 'शाकाहारी',
    'menu.vegan': 'वीगन',
    'menu.nonVeg': 'मांसाहारी',
    'menu.glutenFree': 'ग्लूटेन-मुक्त',
    'menu.noOnionGarlic': 'बिना प्याज/लहसुन',
    'menu.nutAllergy': 'नट एलर्जी',
    'menu.dairyFree': 'डेयरी-मुक्त',
    'menu.uploadPhoto': 'मेनू फोटो अपलोड करें',
    'menu.uploadDesc': 'फोटो लें या मेनू की छवि अपलोड करें',
    'menu.takePhoto': 'फोटो लें',
    'menu.uploadImage': 'अपलोड करें',
    'menu.translateMenu': 'मेनू का अनुवाद करें',
    'menu.translating': 'अनुवाद हो रहा है...',
    'menu.newPhoto': 'नई फोटो',
    'menu.reTranslate': 'पुनः अनुवाद',
    'menu.dishesFound': 'व्यंजन मिले',
    'menu.original': 'मूल',
    'menu.list': 'सूची',
    'menu.overlay': 'ओवरले',
    'menu.ingredients': 'सामग्री',
    'menu.fileTooLarge': 'फाइल बहुत बड़ी है',
    'menu.fileTooLargeDesc': 'कृपया 10MB से कम की छवि चुनें',
    'menu.translationFailed': 'अनुवाद विफल',
    'menu.tryAgain': 'स्पष्ट छवि के साथ पुनः प्रयास करें',
    'menu.menuTranslated': 'मेनू का अनुवाद हो गया!',
    'menu.foundDishes': '{language} में {count} व्यंजन मिले',
    'common.loading': 'लोड हो रहा है...',
    'common.error': 'त्रुटि',
    'common.success': 'सफलता',
    'common.cancel': 'रद्द करें',
    'common.save': 'सहेजें',
    'common.delete': 'हटाएं',
    'common.edit': 'संपादित करें',
    'common.close': 'बंद करें',
    'common.language': 'भाषा',
    'footer.tagline': 'SakuraTrip • AI यात्रा योजना',
  },
  te: {
    'nav.tripPlanner': 'ట్రిప్ ప్లానర్',
    'nav.workspaces': 'వర్క్‌స్పేస్‌లు',
    'nav.tools': 'సాధనాలు',
    'hero.title': 'మీ సరైన ప్రయాణాన్ని ప్లాన్ చేయండి',
    'hero.subtitle': 'AI-ఆధారిత ప్రయాణ సిఫార్సులు',
    'hero.getStarted': 'ప్రారంభించండి',
    'tools.title': 'సాంస్కృతిక సాధనాలు',
    'tools.subtitle': 'AI సహాయంతో స్థానిక సంస్కృతిని అర్థం చేసుకోండి',
    'tools.menuTranslator': 'మెను అనువాదకుడు',
    'tools.menuTranslatorDesc': 'మెను ఫోటో తీసి తక్షణ అనువాదం పొందండి',
    'tools.slangGuide': 'స్లాంగ్ & మర్యాద',
    'tools.slangGuideDesc': 'స్థానిక పదబంధాలు మరియు ఆచారాల త్వరిత గైడ్',
    'tools.comingSoon': 'త్వరలో',
    'tools.openTool': 'తెరువు',
    'menu.title': 'మెను అనువాదకుడు',
    'menu.subtitle': 'మెను ఫోటో అప్‌లోడ్ చేసి తక్షణ అనువాదం పొందండి',
    'menu.backToTools': 'సాధనాలకు తిరిగి',
    'menu.dietaryPrefs': 'ఆహార ప్రాధాన్యతలు',
    'menu.dietaryPrefsDesc': 'అనుకూల వంటకాలను హైలైట్ చేయడానికి మీ అవసరాలను ఎంచుకోండి',
    'menu.vegetarian': 'శాకాహారం',
    'menu.vegan': 'వీగన్',
    'menu.nonVeg': 'మాంసాహారం',
    'menu.glutenFree': 'గ్లూటెన్-ఫ్రీ',
    'menu.noOnionGarlic': 'ఉల్లి/వెల్లుల్లి లేకుండా',
    'menu.nutAllergy': 'నట్ అలర్జీ',
    'menu.dairyFree': 'డెయిరీ-ఫ్రీ',
    'menu.uploadPhoto': 'మెను ఫోటో అప్‌లోడ్ చేయండి',
    'menu.uploadDesc': 'ఫోటో తీయండి లేదా మెను చిత్రాన్ని అప్‌లోడ్ చేయండి',
    'menu.takePhoto': 'ఫోటో తీయండి',
    'menu.uploadImage': 'అప్‌లోడ్',
    'menu.translateMenu': 'మెను అనువదించు',
    'menu.translating': 'అనువదిస్తోంది...',
    'menu.newPhoto': 'కొత్త ఫోటో',
    'menu.reTranslate': 'మళ్ళీ అనువదించు',
    'menu.dishesFound': 'వంటకాలు కనుగొనబడ్డాయి',
    'menu.original': 'అసలు',
    'menu.list': 'జాబితా',
    'menu.overlay': 'ఓవర్లే',
    'menu.ingredients': 'పదార్థాలు',
    'menu.fileTooLarge': 'ఫైల్ చాలా పెద్దది',
    'menu.fileTooLargeDesc': 'దయచేసి 10MB కంటే తక్కువ చిత్రాన్ని ఎంచుకోండి',
    'menu.translationFailed': 'అనువాదం విఫలమైంది',
    'menu.tryAgain': 'స్పష్టమైన చిత్రంతో మళ్ళీ ప్రయత్నించండి',
    'menu.menuTranslated': 'మెను అనువదించబడింది!',
    'menu.foundDishes': '{language}లో {count} వంటకాలు కనుగొనబడ్డాయి',
    'common.loading': 'లోడ్ అవుతోంది...',
    'common.error': 'లోపం',
    'common.success': 'విజయం',
    'common.cancel': 'రద్దు',
    'common.save': 'సేవ్',
    'common.delete': 'తొలగించు',
    'common.edit': 'సవరించు',
    'common.close': 'మూసివేయి',
    'common.language': 'భాష',
    'footer.tagline': 'SakuraTrip • AI ప్రయాణ ప్రణాళిక',
  },
  es: {
    'nav.tripPlanner': 'Planificador',
    'nav.workspaces': 'Espacios',
    'nav.tools': 'Herramientas',
    'hero.title': 'Planifica tu viaje perfecto',
    'hero.subtitle': 'Recomendaciones impulsadas por IA',
    'hero.getStarted': 'Comenzar',
    'tools.title': 'Herramientas culturales',
    'tools.subtitle': 'Navega la cultura local con asistencia de IA',
    'tools.menuTranslator': 'Traductor de menú',
    'tools.menuTranslatorDesc': 'Toma una foto del menú y obtén traducción instantánea',
    'tools.slangGuide': 'Jerga y etiqueta',
    'tools.slangGuideDesc': 'Guía rápida de frases y costumbres locales',
    'tools.comingSoon': 'Próximamente',
    'tools.openTool': 'Abrir',
    'menu.title': 'Traductor de menú',
    'menu.subtitle': 'Sube una foto del menú y obtén traducción instantánea',
    'menu.backToTools': 'Volver a herramientas',
    'menu.dietaryPrefs': 'Preferencias dietéticas',
    'menu.dietaryPrefsDesc': 'Selecciona tus requisitos para resaltar platos compatibles',
    'menu.vegetarian': 'Vegetariano',
    'menu.vegan': 'Vegano',
    'menu.nonVeg': 'No vegetariano',
    'menu.glutenFree': 'Sin gluten',
    'menu.noOnionGarlic': 'Sin cebolla/ajo',
    'menu.nutAllergy': 'Alergia a nueces',
    'menu.dairyFree': 'Sin lácteos',
    'menu.uploadPhoto': 'Subir foto del menú',
    'menu.uploadDesc': 'Toma una foto o sube una imagen del menú',
    'menu.takePhoto': 'Tomar foto',
    'menu.uploadImage': 'Subir',
    'menu.translateMenu': 'Traducir menú',
    'menu.translating': 'Traduciendo...',
    'menu.newPhoto': 'Nueva foto',
    'menu.reTranslate': 'Retraducir',
    'menu.dishesFound': 'Platos encontrados',
    'menu.original': 'Original',
    'menu.list': 'Lista',
    'menu.overlay': 'Superposición',
    'menu.ingredients': 'Ingredientes',
    'menu.fileTooLarge': 'Archivo muy grande',
    'menu.fileTooLargeDesc': 'Selecciona una imagen de menos de 10MB',
    'menu.translationFailed': 'Traducción fallida',
    'menu.tryAgain': 'Intenta con una imagen más clara',
    'menu.menuTranslated': '¡Menú traducido!',
    'menu.foundDishes': '{count} platos encontrados en {language}',
    'common.loading': 'Cargando...',
    'common.error': 'Error',
    'common.success': 'Éxito',
    'common.cancel': 'Cancelar',
    'common.save': 'Guardar',
    'common.delete': 'Eliminar',
    'common.edit': 'Editar',
    'common.close': 'Cerrar',
    'common.language': 'Idioma',
    'footer.tagline': 'SakuraTrip • Planificación de viajes con IA',
  },
  zh: {
    'nav.tripPlanner': '行程规划',
    'nav.workspaces': '工作空间',
    'nav.tools': '工具',
    'hero.title': '规划完美旅程',
    'hero.subtitle': 'AI驱动的旅行建议',
    'hero.getStarted': '开始',
    'tools.title': '文化工具',
    'tools.subtitle': '借助AI了解当地文化',
    'tools.menuTranslator': '菜单翻译器',
    'tools.menuTranslatorDesc': '拍摄菜单照片，即时获取翻译和饮食信息',
    'tools.slangGuide': '俚语与礼仪',
    'tools.slangGuideDesc': '当地短语和习俗快速指南',
    'tools.comingSoon': '即将推出',
    'tools.openTool': '打开',
    'menu.title': '菜单翻译器',
    'menu.subtitle': '上传菜单照片，即时获取翻译和饮食信息',
    'menu.backToTools': '返回工具',
    'menu.dietaryPrefs': '饮食偏好',
    'menu.dietaryPrefsDesc': '选择您的饮食需求以突出显示兼容菜品',
    'menu.vegetarian': '素食',
    'menu.vegan': '纯素',
    'menu.nonVeg': '非素食',
    'menu.glutenFree': '无麸质',
    'menu.noOnionGarlic': '无葱蒜',
    'menu.nutAllergy': '坚果过敏',
    'menu.dairyFree': '无乳制品',
    'menu.uploadPhoto': '上传菜单照片',
    'menu.uploadDesc': '拍照或上传菜单图片',
    'menu.takePhoto': '拍照',
    'menu.uploadImage': '上传',
    'menu.translateMenu': '翻译菜单',
    'menu.translating': '翻译中...',
    'menu.newPhoto': '新照片',
    'menu.reTranslate': '重新翻译',
    'menu.dishesFound': '找到菜品',
    'menu.original': '原文',
    'menu.list': '列表',
    'menu.overlay': '叠加',
    'menu.ingredients': '食材',
    'menu.fileTooLarge': '文件太大',
    'menu.fileTooLargeDesc': '请选择小于10MB的图片',
    'menu.translationFailed': '翻译失败',
    'menu.tryAgain': '请使用更清晰的图片重试',
    'menu.menuTranslated': '菜单已翻译！',
    'menu.foundDishes': '在{language}中找到{count}道菜品',
    'common.loading': '加载中...',
    'common.error': '错误',
    'common.success': '成功',
    'common.cancel': '取消',
    'common.save': '保存',
    'common.delete': '删除',
    'common.edit': '编辑',
    'common.close': '关闭',
    'common.language': '语言',
    'footer.tagline': 'SakuraTrip • AI旅行规划',
  },
  pt: {
    'nav.tripPlanner': 'Planejador',
    'nav.workspaces': 'Espaços',
    'nav.tools': 'Ferramentas',
    'hero.title': 'Planeje sua viagem perfeita',
    'hero.subtitle': 'Recomendações com IA',
    'hero.getStarted': 'Começar',
    'tools.title': 'Ferramentas culturais',
    'tools.subtitle': 'Navegue pela cultura local com assistência de IA',
    'tools.menuTranslator': 'Tradutor de cardápio',
    'tools.menuTranslatorDesc': 'Tire uma foto do cardápio e obtenha tradução instantânea',
    'tools.slangGuide': 'Gírias e etiqueta',
    'tools.slangGuideDesc': 'Guia rápido de frases e costumes locais',
    'tools.comingSoon': 'Em breve',
    'tools.openTool': 'Abrir',
    'menu.title': 'Tradutor de cardápio',
    'menu.subtitle': 'Envie uma foto do cardápio e obtenha tradução instantânea',
    'menu.backToTools': 'Voltar às ferramentas',
    'menu.dietaryPrefs': 'Preferências alimentares',
    'menu.dietaryPrefsDesc': 'Selecione seus requisitos para destacar pratos compatíveis',
    'menu.vegetarian': 'Vegetariano',
    'menu.vegan': 'Vegano',
    'menu.nonVeg': 'Não vegetariano',
    'menu.glutenFree': 'Sem glúten',
    'menu.noOnionGarlic': 'Sem cebola/alho',
    'menu.nutAllergy': 'Alergia a nozes',
    'menu.dairyFree': 'Sem laticínios',
    'menu.uploadPhoto': 'Enviar foto do cardápio',
    'menu.uploadDesc': 'Tire uma foto ou envie uma imagem do cardápio',
    'menu.takePhoto': 'Tirar foto',
    'menu.uploadImage': 'Enviar',
    'menu.translateMenu': 'Traduzir cardápio',
    'menu.translating': 'Traduzindo...',
    'menu.newPhoto': 'Nova foto',
    'menu.reTranslate': 'Retraduzir',
    'menu.dishesFound': 'Pratos encontrados',
    'menu.original': 'Original',
    'menu.list': 'Lista',
    'menu.overlay': 'Sobreposição',
    'menu.ingredients': 'Ingredientes',
    'menu.fileTooLarge': 'Arquivo muito grande',
    'menu.fileTooLargeDesc': 'Selecione uma imagem menor que 10MB',
    'menu.translationFailed': 'Falha na tradução',
    'menu.tryAgain': 'Tente com uma imagem mais clara',
    'menu.menuTranslated': 'Cardápio traduzido!',
    'menu.foundDishes': '{count} pratos encontrados em {language}',
    'common.loading': 'Carregando...',
    'common.error': 'Erro',
    'common.success': 'Sucesso',
    'common.cancel': 'Cancelar',
    'common.save': 'Salvar',
    'common.delete': 'Excluir',
    'common.edit': 'Editar',
    'common.close': 'Fechar',
    'common.language': 'Idioma',
    'footer.tagline': 'SakuraTrip • Planejamento de viagens com IA',
  },
};

interface LanguageContextType {
  language: SupportedLanguage;
  setLanguage: (lang: SupportedLanguage) => void;
  t: (key: string, params?: Record<string, string | number>) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const STORAGE_KEY = 'sakuratrip-language';

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<SupportedLanguage>(() => {
    const stored = localStorage.getItem(STORAGE_KEY);
    return (stored as SupportedLanguage) || 'en';
  });

  useEffect(() => {
    localStorage.setItem(STORAGE_KEY, language);
    // Set HTML lang attribute for accessibility
    document.documentElement.lang = language;
  }, [language]);

  const setLanguage = (lang: SupportedLanguage) => {
    setLanguageState(lang);
  };

  const t = (key: string, params?: Record<string, string | number>): string => {
    let text = translations[language][key] || translations['en'][key] || key;
    
    if (params) {
      Object.entries(params).forEach(([paramKey, value]) => {
        text = text.replace(`{${paramKey}}`, String(value));
      });
    }
    
    return text;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
